package com.mls.logistics.domain;

import com.mls.logistics.exception.InvalidRequestException;

/**
 * Type of a stock {@link Movement}.
 *
 * <ul>
 *   <li>{@code ENTRY} — stock quantity increased</li>
 *   <li>{@code EXIT} — stock quantity decreased</li>
 *   <li>{@code TRANSFER} — reserved for warehouse-to-warehouse moves
 *       (kept for legacy rows; not generated by the current system)</li>
 * </ul>
 *
 * <p>Movements are system-generated by {@code StockService} whenever stock
 * changes; they are never created or modified through the API (the audit
 * trail is append-only).</p>
 */
public enum MovementType {

    ENTRY,
    EXIT,
    TRANSFER;

    /**
     * Parses a status string (case-insensitive, trimmed).
     *
     * @throws InvalidRequestException if the value is not a known type
     */
    public static MovementType from(String value) {
        if (value == null || value.isBlank()) {
            throw new InvalidRequestException("Movement type is required.");
        }
        try {
            return MovementType.valueOf(value.trim().toUpperCase());
        } catch (IllegalArgumentException ex) {
            throw new InvalidRequestException(
                "Unknown movement type: '" + value + "'. Valid values: ENTRY, EXIT, TRANSFER.");
        }
    }
}
