-- =====================================================================
-- MOLS baseline schema (V1)
--
-- This baseline is generated from the JPA entity model and is the single
-- source of truth for the database schema. Hibernate runs in `validate`
-- mode against it (see application.properties), so any drift between the
-- entities and these tables fails fast at startup.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Master data
-- ---------------------------------------------------------------------
CREATE TABLE units (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name     VARCHAR(255),
    location VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE warehouses (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name     VARCHAR(255),
    location VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE resources (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255),
    type        VARCHAR(255),
    criticality VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE vehicles (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    type     VARCHAR(255),
    capacity INTEGER NOT NULL,
    status   VARCHAR(255),
    PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------
-- Stock
-- ---------------------------------------------------------------------
CREATE TABLE stocks (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    resource_id  BIGINT,
    warehouse_id BIGINT,
    quantity     INTEGER NOT NULL,
    PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------
-- Orders
-- ---------------------------------------------------------------------
CREATE TABLE orders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    unit_id      BIGINT,
    date_created DATE,
    status       VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE TABLE order_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id    BIGINT,
    resource_id BIGINT,
    quantity    INTEGER NOT NULL,
    PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------
-- Shipments
-- ---------------------------------------------------------------------
CREATE TABLE shipments (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id     BIGINT,
    vehicle_id   BIGINT,
    warehouse_id BIGINT,
    status       VARCHAR(255),
    PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------
-- Movements (stock audit trail)
-- ---------------------------------------------------------------------
CREATE TABLE movements (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    stock_id    BIGINT,
    type        VARCHAR(255),
    quantity    INTEGER NOT NULL,
    date_time   TIMESTAMP(6),
    order_id    BIGINT,
    shipment_id BIGINT,
    reason      VARCHAR(200),
    PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------
-- Application users (authentication / authorization)
-- ---------------------------------------------------------------------
CREATE TABLE app_users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(255) NOT NULL CHECK (role IN ('ADMIN', 'OPERATOR', 'AUDITOR')),
    enabled  BOOLEAN,
    PRIMARY KEY (id)
);

-- ---------------------------------------------------------------------
-- Foreign keys
-- ---------------------------------------------------------------------
ALTER TABLE stocks      ADD CONSTRAINT fk_stocks_resource       FOREIGN KEY (resource_id)  REFERENCES resources (id);
ALTER TABLE stocks      ADD CONSTRAINT fk_stocks_warehouse      FOREIGN KEY (warehouse_id) REFERENCES warehouses (id);

ALTER TABLE orders      ADD CONSTRAINT fk_orders_unit           FOREIGN KEY (unit_id)      REFERENCES units (id);

ALTER TABLE order_items ADD CONSTRAINT fk_order_items_order     FOREIGN KEY (order_id)     REFERENCES orders (id);
ALTER TABLE order_items ADD CONSTRAINT fk_order_items_resource  FOREIGN KEY (resource_id)  REFERENCES resources (id);

ALTER TABLE shipments   ADD CONSTRAINT fk_shipments_order       FOREIGN KEY (order_id)     REFERENCES orders (id);
ALTER TABLE shipments   ADD CONSTRAINT fk_shipments_vehicle     FOREIGN KEY (vehicle_id)   REFERENCES vehicles (id);
ALTER TABLE shipments   ADD CONSTRAINT fk_shipments_warehouse   FOREIGN KEY (warehouse_id) REFERENCES warehouses (id);

ALTER TABLE movements   ADD CONSTRAINT fk_movements_stock       FOREIGN KEY (stock_id)     REFERENCES stocks (id);
