-- =====================================================================
-- MOLS V6 — Shipment line items and partial order fulfillment
--
-- Previously a shipment linked to a whole order with no item/quantity
-- breakdown, and delivering a shipment only did anything once EVERY
-- shipment of the order was DELIVERED — delivering the first of several
-- shipments silently produced no stock change and no audit trail entry.
--
-- This adds shipment_items, mirroring the existing order_items junction
-- (parent FK + resource-bearing FK + positive quantity), so each shipment
-- carries a specific subset of an order's items with its own quantity.
-- Delivery now deducts stock per shipment; the order becomes
-- PARTIALLY_SHIPPED once some (not all) items are delivered, and
-- COMPLETED once every item is fully delivered.
-- =====================================================================

CREATE TABLE shipment_items (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    shipment_id   BIGINT NOT NULL,
    order_item_id BIGINT NOT NULL,
    quantity      INTEGER NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE shipment_items ADD CONSTRAINT fk_shipment_items_shipment
    FOREIGN KEY (shipment_id) REFERENCES shipments (id);
ALTER TABLE shipment_items ADD CONSTRAINT fk_shipment_items_order_item
    FOREIGN KEY (order_item_id) REFERENCES order_items (id);

ALTER TABLE shipment_items ADD CONSTRAINT chk_shipment_items_quantity_positive
    CHECK (quantity > 0);

CREATE INDEX idx_shipment_items_shipment   ON shipment_items (shipment_id);
CREATE INDEX idx_shipment_items_order_item ON shipment_items (order_item_id);

-- Order status: add PARTIALLY_SHIPPED between the open statuses and
-- COMPLETED (see OrderStatus.canTransitionTo for the full state machine).
ALTER TABLE orders DROP CONSTRAINT chk_orders_status;
ALTER TABLE orders ADD CONSTRAINT chk_orders_status
    CHECK (status IN ('CREATED', 'VALIDATED', 'PARTIALLY_SHIPPED', 'COMPLETED', 'CANCELLED'));
